services:
  - type: web
    name: topsis-web-service
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.headless true --server.enableCORS false --server.enableXsrfProtection false --server.port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.4
    plan: free